name: Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Frontend to Github Registry
        uses: docker/build-push-action@v1
        with:
          path: ./frontend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: shynixn/bracket/frontend
          tag_with_ref: true

      - name: Deploy Backend to Github Registry
        uses: docker/build-push-action@v1
        with:
          path: ./backend
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: shynixn/bracket/backend
          tag_with_ref: true
